export const DYNAMIC_COMPONENT_INIT = 'DYNAMIC_COMPONENT_INIT';
export const DYNAMIC_COMPONENT_INIT_WITH_STATE =  'DYNAMIC_COMPONENT_INIT_WITH_STATE';

export const SAVE_ENTITY_DATA = 'SAVE_ENTITY_DATA';

export const DYNAMIC_COMPONENT_SAVE_DATA = 'DYNAMIC_COMPONENT_SAVE_DATA';
export const DYNAMIC_COMPONENT_SAVE_DATA_ERROR =  'DYNAMIC_COMPONENT_SAVE_DATA_ERROR';

